name: _
publish_to: none

workspace:
  - services/rest_api_server
  - packages/logic
  - clients/mobile/deenly

environment:
  sdk: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

scripts: 
  deps: fvm flutter pub get 